### ISSUE TITLE
Объявление может иметь несколько изображений

### ISSUE THREAD

**Issue by RagunovichVlad** [ErmolkinVlad/ad_service#23]
Объявление может иметь несколько изображений

Этот гем значительно упростит задачу
https://github.com/nathanvda/cocoon

**Comment by ErmolkinVlad** [comment]
![screenshot from 2017-02-23 00-44-31](https://cloud.githubusercontent.com/assets/11902012/23233893/58f86448-f961-11e6-86c6-cf9fbe07bb54.png)

**Comment by ErmolkinVlad** [comment]
Оно же вроде и так имеет несколько изображений.
