### ISSUE TITLE
Rails 5 redirect_back method

### ISSUE THREAD

**Issue by RagunovichVlad** [ErmolkinVlad/ad_service#26]
https://github.com/ErmolkinVlad/ad_service/blob/master/app/controllers/adverts_controller.rb#L78

В рельсе есть специальный метод для редиректа на предыдущую страницу
http://blog.bigbinary.com/2016/02/29/rails-5-improves-redirect_to_back-with-redirect-back.html

**Comment by ErmolkinVlad** [comment]
Этот метод используется в edit, чтобы сохранить точку входа в него. А потом перенаправить в нее из update. Если использовать redirect_back в update, то бросает обратно в edit.

**Comment by ErmolkinVlad** [comment]
Исправил. Теперь после обновления пользователя перенаправляет на страницу просмотра объявления.
`  def update
    if @advert.update(advert_params)
      @advert.refresh!
      @advert.create_log(@advert.user)
      redirect_to [@user, @advert]
    else
      render action: 'edit'
    end
  end`
