### ISSUE TITLE
Commit Messages

### ISSUE THREAD

**Issue by RagunovichVlad** [ErmolkinVlad/ad_service#3]
http://chris.beams.io/posts/git-commit/

**Comment by RagunovichVlad** [comment]
It's not very important to creates releases and you don't need to specify version in commit message

**Comment by RagunovichVlad** [comment]
`invoke cancan and better main page` такие комиты не надо делать
Должно быть 2 комита: `Add cancan` и `Change main page view`

**Comment by ErmolkinVlad** [comment]
OK. Understood.

**Comment by RagunovichVlad** [comment]
Старайся писать как можно более понятные описания комитов. Например "Change something ... because of ...", вместо "Fix".
По теме:
* http://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message
* http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

Менять ничего не нужно, это инфа на будущее. Как прочтешь - закрывай.
